### ISSUE TITLE
TypeError: object of type 'numpy.float64' has no len(): len(self.ascna_based_model.centroids) 

### ISSUE THREAD

**Issue by lelagina-broad** [broadinstitute/deTiN#23]
I recently encountered this error across several CLL samples:
```
Traceback (most recent call last):
  File "/root/deTiN/deTiN/deTiN.py", line 606, in <module>
    main()
  File "/root/deTiN/deTiN/deTiN.py", line 565, in main
    do.calculate_joint_estimate()
  File "/root/deTiN/deTiN/deTiN.py", line 266, in calculate_joint_estimate
    if len(self.ascna_based_model.centroids) > 1:
TypeError: object of type 'numpy.float64' has no len()
```
Here is the code that initializes object ascna_based_model:
```
import deTiN_aSCNA_based_estimate as dascna
ascna_based_model = dascna.model(di.seg_table, di.het_table, di.resolution)
```
When I checked the centroids parameter for the object it is initialized to numpy array in the __init__ function:
```
 self.centroids = np.zeros([3, 1])
```
I am not sure where in the code it is reinitialized and hence fails this condition:
```
if len(self.ascna_based_model.centroids) > 1:
```

**Comment by amarotaylor** [comment]
I fixed this issue. Please try rerunning
